resources:
  - nginx_deployment.yaml

# Use ConfigMapGenerator instead of direct ConfigMap reference
configMapGenerator:
  - name: nginx-image-config
    behavior: merge  # This will merge with existing ConfigMap instead of replacing it
    literals:
      - tag=1.25.0  # Default value, will be overridden by existing ConfigMap

replacements:
  - source:
      kind: ConfigMap
      name: nginx-image-config
      fieldPath: data.tag
    targets:
      - select:
          kind: Deployment
          name: nginx-deployment
        fieldPaths:
          - spec.template.spec.containers.[name=nginx].image
        options:
          delimiter: ":"
          index: 1