resources:
  - nginx_deployment.yaml
  # Removing configmap.yaml so ArgoCD won't manage it


replacements:
  # Add a replacement for the ConfigMap hash to force deployment updates
  - source:
      kind: ConfigMap
      name: nginx-image-config
      fieldPath: data.tag
    targets:
      - select:
          kind: Deployment
          name: nginx-deployment
        fieldPaths:
          - metadata.annotations.configmap-tag-hash
          - spec.template.metadata.annotations.configmap-tag-hash