apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
  annotations:
    # This will cause the deployment to restart when the ConfigMap changes
    configmap-tag-hash: "${CONFIGMAP_TAG_HASH}"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        # This will cause the pods to restart when the ConfigMap changes
        configmap-tag-hash: "${CONFIGMAP_TAG_HASH}"
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80 